### Get user's messages in a channel
GET http://localhost:8080/chat/veibae?username=afnos_

###  Get user's messages filtered by a regex
GET http://localhost:8080/chat/sodapoppin?username=afnos_

### Get server status
GET http://localhost:8080/service/status

### Get configuration
GET http://localhost:8080/service/config

### Test bad request
GET http://localhost:8080/chat/nyanners?username=afnos_

### Test add channel
PUT http://localhost:8080/chat/ewica 

### Test delete channel
DELETE http://localhost:8080/chat/sodapoppin

### Test limit and skip
GET http://localhost:8080/chat/nyanners?username=afnos_&regex=vei&limit=2&skip=5