### Get user's messages in a channel
GET http://localhost:8080/chat/veibae?username=a

### Get server status
GET http://localhost:8080/service/status

### Get configuration
GET http://localhost:8080/service/config

### Test bad request
GET http://localhost:8080/chat/nyanners?username=a

### Test add channel
PUT http://localhost:8080/chat/nyanners

###
PUT http://localhost:8080/chat/Jerma985

###
GET http://localhost:8080/chat/Jerma985?username=a

### Test delete channel
DELETE http://localhost:8080/chat/sodapoppin

### Test limit and skip
GET http://localhost:8080/chat/nyanners?username=a&regex=vei&limit=5&skip=5