services:
  twitchlogger:
    container_name: twitchlogger
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TIME_ZONE: Mountain/US
    ports:
      - 8080:8080
  mongodb:
    image: mongo
    container_name: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes: 
      - ./data/db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped